version: '3.1'
services:
  glitch-me:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: glitch-me
    image: glitch-me
    volumes:
      - .:/app/
